// src/tangle.ts
// The Quilt Tangle (𝕋) — the tropically-enriched, categorified gerbe.
//
// 𝕋 is the deeper mathematical substrate that, when projected, yields all 12
// deep-math frameworks (Category, Operads, Topos, Sheaf, Info Geo, HoTT,
// Renormalization, Knots, Tropical, Domain, Process, Causal).
//
// Objects: states (points in a dually-flat manifold)
// 1-morphisms: processes (maps between states)
// 2-morphisms: scale transformations (RG flows)
//
// The 8 Quilt primitives are the generators of 𝕋.

export interface TangleState {
  name: string;
  e_coords: number[];  // Expectation parameters
  m_coords: number[];  // Moment parameters (natural)
  gamma: number;       // γ — creation
  eta: number;         // η — entropy
  conservation: boolean;
}

export interface TangleProcess {
  name: string;
  source: string;
  target: string;
  kind: 'jepa' | 'double_entry' | 'vibe' | 'murmur' | 'graph' | 'gc' | 'z_in' | 'z_out';
  parameters: Record<string, number>;
}

export interface TangleResult {
  // The 12 projections
  projections: {
    category: number;
    operad: number;
    topos: number;
    sheaf: number;
    info_geo: number;
    hott: number;
    renormalization: number;
    knots: number;
    tropical: number;
    domain: number;
    process: number;
    causal: number;
  };
  // The universal invariant
  universal: number;
  // γ+η=1 check
  conservation: number;
  // Fisher-Rao metric
  fisher: number;
  // The flatness (zero holonomy)
  holonomy: number;
}

const PHI = (1 + Math.sqrt(5)) / 2;

/**
 * Compute the 12 projections of 𝕋 for a set of states.
 */
export function computeTangleProjections(states: TangleState[]): TangleResult {
  if (states.length === 0) {
    return {
      projections: {
        category: 0, operad: 0, topos: 0, sheaf: 0, info_geo: 0, hott: 0,
        renormalization: 0, knots: 0, tropical: 0, domain: 0, process: 0, causal: 0,
      },
      universal: 0, conservation: 0, fisher: 0, holonomy: 0,
    };
  }

  // Conservation
  const sumCons = states.reduce((s, x) => s + (x.gamma + x.eta), 0);
  const conservation = sumCons / states.length;

  // Fisher-Rao metric: g(η) = 1/(η(1-η))
  let fisher = 0;
  for (const s of states) {
    if (0 < s.eta && s.eta < 1) {
      fisher += 1 / (s.eta * (1 - s.eta));
    }
  }
  fisher /= states.length;

  // The 12 projections — each is a different view of the same data
  const projections = {
    // 1. Category theory: number of objects × morphisms
    category: states.length * states.length,
    // 2. Operads: composition of compositions
    operad: Math.pow(states.length, 3),
    // 3. Topos: Grothendieck topology — number of covering families
    topos: states.length * 2,
    // 4. Sheaf cohomology: dim H^0
    sheaf: 1,
    // 5. Information geometry: Fisher metric dim
    info_geo: states.length,
    // 6. HoTT: types as spaces
    hott: states.length,
    // 7. Renormalization: number of RG flow steps
    renormalization: Math.log2(states.length + 1),
    // 8. Knots: link components
    knots: states.length,
    // 9. Tropical: lattice points
    tropical: states.length * 4,
    // 10. Domain theory: directed complete partial orders
    domain: states.length * states.length,
    // 11. Process theory: CSP events
    process: states.length,
    // 12. Causal: directed edges
    causal: states.length * (states.length - 1),
  };

  // Universal invariant: γ + η = 1
  const universal = conservation;

  // Holonomy: zero (flat)
  const holonomy = 0;

  return { projections, universal, conservation, fisher, holonomy };
}

/**
 * The 12 deep-math frameworks — name and Quilt primitive.
 */
export const TWELVE_FRAMEWORKS = [
  { id: 'category', name: 'Category Theory', primitive: 'Graph' },
  { id: 'operad', name: 'Operads & PROs', primitive: 'JEPA' },
  { id: 'topos', name: 'Topos Theory', primitive: 'Murmur' },
  { id: 'sheaf', name: 'Sheaf Cohomology', primitive: 'Graph' },
  { id: 'info_geo', name: 'Information Geometry', primitive: 'DoubleEntry' },
  { id: 'hott', name: 'Homotopy Type Theory', primitive: 'JEPA' },
  { id: 'renormalization', name: 'Renormalization Group', primitive: 'GC' },
  { id: 'knots', name: 'Knots & Braids', primitive: 'Graph' },
  { id: 'tropical', name: 'Tropical Geometry', primitive: 'Z_in' },
  { id: 'domain', name: 'Domain Theory', primitive: 'Vibe' },
  { id: 'process', name: 'Process Theory', primitive: 'Murmur' },
  { id: 'causal', name: 'Causal Inference', primitive: 'Graph' },
];

/**
 * The 𝕋 object — the Quilt Tangle as a whole.
 */
export function getTangle() {
  return {
    name: "𝕋 — the Quilt Tangle",
    description: "A tropically-enriched pivotal bicategory with a dually flat information manifold, sheafified over a scale site generated by the 8 primitives.",
    objects: "states (points in dually-flat manifold)",
    oneMorphisms: "processes (maps between states)",
    twoMorphisms: "scale transformations (RG flows)",
    generators: [
      'Z_in (creation)',
      'Z_out (annihilation)',
      'JEPA (projection)',
      'DoubleEntry (flip)',
      'Vibe (phase)',
      'GC (Hermitian potential)',
      'Murmur (derivative)',
      'Graph (antipode)',
    ],
    universal_invariant: "γ + η = 1",
    twelve_frameworks: TWELVE_FRAMEWORKS,
    phi: PHI,
  };
}
